test:
  tags:
    - main
  script:
    - echo 'Testing ...'
    - echo 'Success'
  only: 
    - master

deploy:
  tags:
    - main
  type: deploy
  when: manual
  script:
    - echo 'Deploying ...'
    - ./build.sh
    - echo 'Success'
  only: 
    - master
