# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Рекламодатель'), (1, 'Владелец сайта')], null=True, verbose_name='Роль'),
        ),
    ]
