# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 15:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено в')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано в')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
                ('title', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('text', models.TextField(max_length=300, verbose_name='Текст')),
                ('link', models.URLField(blank=True, max_length=256, null=True, verbose_name='Ссылка перехода')),
                ('max_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Макс. трат')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name_plural': 'рекламные кампании',
                'ordering': ['-created'],
                'verbose_name': 'Рекламная кампания',
            },
        ),
        migrations.CreateModel(
            name='ASite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено в')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано в')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
                ('title', models.CharField(max_length=100, verbose_name='Название сайта')),
                ('topic', models.CharField(max_length=100, verbose_name='Тип площадки')),
                ('link', models.URLField(max_length=256, verbose_name='Домен сайта')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name_plural': 'рекламные площадки',
                'ordering': ['-created'],
                'verbose_name': 'Рекламная площадка',
            },
        ),
        migrations.CreateModel(
            name='ImageAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено в')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано в')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
                ('image', models.ImageField(upload_to='images', verbose_name='Файл картинки')),
                ('weight', models.IntegerField(default=1, verbose_name='Вес картинки')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ACompany', verbose_name='Рекламная компания')),
            ],
            options={
                'verbose_name_plural': 'картинки',
                'ordering': ['-weight'],
                'verbose_name': 'Картинка',
            },
        ),
    ]
