# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemporalGrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=64, verbose_name='Токен')),
                ('token_type', models.CharField(choices=[('Bearer', 'Bearer')], max_length=30, verbose_name='Тип')),
                ('expires_in', models.DateTimeField(verbose_name='Протухнет в')),
                ('app_name', models.CharField(max_length=30, verbose_name='Приложение')),
            ],
            options={
                'verbose_name': 'Токен доступа',
                'verbose_name_plural': 'токены доступа',
            },
        ),
    ]
