# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.UUIDField(verbose_name='ID компании')),
                ('image', models.UUIDField(blank=True, null=True, verbose_name='ID картинки')),
                ('site', models.UUIDField(verbose_name='ID площадки')),
                ('accepted', models.DateTimeField(verbose_name='Время создания')),
                ('user_agent', models.CharField(blank=True, max_length=256, null=True, verbose_name='User-agent')),
            ],
            options={
                'verbose_name': 'Показ',
                'ordering': ['-accepted'],
                'verbose_name_plural': 'показы',
            },
        ),
        migrations.CreateModel(
            name='Transit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.DateTimeField(verbose_name='Время создания')),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Display', verbose_name='Показ')),
            ],
            options={
                'verbose_name': 'Переход по рекламе',
                'ordering': ['-accepted'],
                'verbose_name_plural': 'переходы по рекламе',
            },
        ),
    ]
